version: '3.8'

services:

  gramine:
    image: gramine
    build: .
    volumes:
      - .:/root
      - untrustedhost:/root/untrustedhost
    devices:
      - /dev/sgx_enclave:/dev/sgx_enclave
      - /dev/sgx_provision:/dev/sgx_provision
    working_dir: /root
    command: >
      bash -c "
        if [ ! -f nodejs.manifest.sgx ]; then
          SGX=1 make &&
          cd walle && pnpm build && cd .. &&
          gramine-sgx nodejs walle/dist/index.js
        else
          cd walle && pnpm build && cd .. &&
          gramine-sgx nodejs walle/dist/index.js
        fi
      "

volumes:
  untrustedhost:
